import "~/styles/globals.css"

import { ClerkProvider } from "@clerk/nextjs"
import type { Metadata } from "next"
import { Geist } from "next/font/google"

import { env } from "~/env"

export const metadata: Metadata = {
	title: "Nxt bot",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
}

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
})

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<ClerkProvider publishableKey={env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>
			<html className={`${geist.variable}`} lang="en">
				<body>{children}</body>
			</html>
		</ClerkProvider>
	)
}
