import "~/styles/globals.css"

import { ClerkProvider } from "@clerk/nextjs"
import type { Metadata } from "next"
import { Geist, Inter } from "next/font/google"

import { env } from "~/env"
import { cn } from "~/lib/utils"

import { ConvexProvider } from "~/components/convex-provider"

const geistHeading = Geist({ subsets: ["latin"], variable: "--font-heading" })

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" })

export const metadata: Metadata = {
	title: "nxtbot",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
}

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
})

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<ClerkProvider
			appearance={{ theme: "shadcn" }}
			publishableKey={env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
		>
			<ConvexProvider>
				<html
					className={cn(
						geist.variable,
						"font-sans",
						inter.variable,
						geistHeading.variable,
						"dark"
					)}
					lang="en"
					suppressHydrationWarning
				>
					<body>{children}</body>
				</html>
			</ConvexProvider>
		</ClerkProvider>
	)
}
